%          ###########   ###########   ##########    ##########
%         ############  ############  ############  ############
%         ##            ##            ##   ##   ##  ##        ##
%         ##            ##            ##   ##   ##  ##        ##
%         ###########   ####  ######  ##   ##   ##  ##    ######
%          ###########  ####  #       ##   ##   ##  ##    #    #
%                   ##  ##    ######  ##   ##   ##  ##    #    #
%                   ##  ##    #       ##   ##   ##  ##    #    #
%         ############  ##### ######  ##   ##   ##  ##### ######
%         ###########    ###########  ##   ##   ##   ##########
%
%            S E C U R E   M O B I L E   N E T W O R K I N G
% 
% 
% plot_pattern_2d - Plot 2D Antenna Sector Patterns
%
% Other m-files required: mmpolar/mmpolar.m
% Subfunctions: none
% MAT-files required: sectorpattern_2d_sta.mat, sectorpattern_2d_ap.mat
%
% Author: Daniel Steinmetzer
% email address: dsteinmetzer@seemoo.tu-darmstadt.de
% Website: https://ww.seemoo.de
% Date: 2017

%------------- BEGIN CODE --------------

clear; close all;
p_sta = load('sectorpattern_2d_sta.mat');
p_ap = load('sectorpattern_2d_ap.mat');
path('mmpolar',path)

% Plot the TX Patterns
for s = 1:numel(p_sta.sector_set)
    sector_id = string(p_sta.sector_set(s));
    
    figure(s)
    mmpolar(p_sta.az/180*pi, ...
        (p_sta.pattern_snr(:,:,s)),  ...
        'RLimit', [-8, 17], ...
        'TTickDelta', 30, ...
        'TTickLabel', { '0^\circ', '30^\circ', '', '', '', '150^\circ', '180^\circ', '-150^\circ', '', '', '', '-30^\circ'}, ...
        'RGridLineStyle', ':', ...
        'TGridLineStyle', ':', ...
        'TTickOffset', 0.25, ...
        'TTickVisible', 'on', ...
        'TTickDirection', 'out', ...
        'RTickValue', [0, 10], ...
        'RTickVisible', 'off', ...
        'RTickOffset', 0.06, ...
        'Style', 'Compass')
    title(strcat("Sector ", sector_id))
end

% Plot the RX Pattern
s = 34;
sector_id = string(p_ap.sector_set(s));

figure(35)
mmpolar(p_ap.az/180*pi, ...
    (p_ap.pattern_snr(:,:,s)),  ...
    'RLimit', [-8, 17], ...
    'TTickDelta', 30, ...
    'TTickLabel', { '0^\circ', '30^\circ', '', '', '', '150^\circ', '180^\circ', '-150^\circ', '', '', '', '-30^\circ'}, ...
    'RGridLineStyle', ':', ...
    'TGridLineStyle', ':', ...
    'TTickOffset', 0.25, ...
    'TTickVisible', 'on', ...
    'TTickDirection', 'out', ...
    'RTickValue', [0, 10], ...
    'RTickVisible', 'off', ...
    'RTickOffset', 0.06, ...
    'Style', 'Compass')
title(strcat("Sector RX"))

%------------- END OF CODE --------------